// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Url_cutter.Data;

namespace Url_cutter.Migrations
{
    [DbContext(typeof(UrlCutterContextDB))]
    partial class UrlCutterContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("Url_cutter.Models.DataModels.StoredUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseUrl");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("ShortUrl");

                    b.Property<int>("Transition");

                    b.HasKey("Id");

                    b.ToTable("StoredUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
